# Generated by Django 2.1.7 on 2019-03-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.PositiveSmallIntegerField(help_text='Enter the Serial No.', verbose_name='Serial No.')),
                ('name', models.CharField(help_text='Enter the Parameter Name', max_length=200, verbose_name='Parameter Name')),
                ('value', models.CharField(help_text='Enter the Parameter Value', max_length=200, verbose_name='Parameter Value')),
            ],
            options={
                'ordering': ['sno'],
            },
        ),
    ]
