# Generated by Django 2.1.7 on 2019-03-03 07:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Date and Time')),
                ('operation', models.CharField(help_text='Enter the operation type', max_length=30, verbose_name='Operation Type')),
                ('description', models.TextField(help_text='Enter Operation Description', max_length=200, verbose_name='Description')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='process_scada.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='Event Time')),
                ('diagnosis_filter', models.CharField(choices=[('S', 'S'), ('W', 'W'), ('D', 'D')], help_text='Choose the diagnosis filter', max_length=5)),
                ('error_code', models.IntegerField(help_text='Enter the Error Code', verbose_name='Error Code')),
                ('details', models.TextField(blank=True, help_text='Enter the Details of Diagnosis', null=True, verbose_name='Details')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='process_scada.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('sno', models.PositiveSmallIntegerField(help_text='Enter the Serial No.', primary_key=True, serialize=False, verbose_name='Serial No.')),
                ('name', models.CharField(help_text='Enter the Parameter Name', max_length=200, verbose_name='Parameter Name')),
                ('value', models.CharField(help_text='Enter the Parameter Value', max_length=200, verbose_name='Parameter Value')),
                ('description', models.TextField(blank=True, help_text='Enter the Parameter Description', max_length=1000, null=True, verbose_name='Parameter Description')),
            ],
            options={
                'ordering': ['sno'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('time', models.DateTimeField(default=django.utils.timezone.now, help_text='Enter the date and time for the event', primary_key=True, serialize=False, verbose_name='Date and Time')),
                ('types', models.CharField(choices=[('P', 'P'), ('E', 'E')], help_text='Enter the type', max_length=5, verbose_name='Type')),
                ('quantity', models.PositiveIntegerField(help_text='Enter the production quantity in x1000', verbose_name='Quantity')),
                ('comp_mmv', models.CharField(help_text='Enter the Compression force M,MV', max_length=10, verbose_name='Compression Force ( M MV)')),
                ('comp_srel', models.CharField(help_text='Enter compression force Srel %', max_length=10, verbose_name='Compression force( SRel %)')),
                ('comp_pmv', models.CharField(help_text='Enter the compression force P MV', max_length=10, verbose_name='Compression Force ( P MV) ')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='process_scada.Batch')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_scada.Product'),
        ),
    ]
