# Generated by Django 2.1.7 on 2019-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_scada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('diagnosis_filter', models.CharField(choices=[('S', 'S'), ('W', 'W'), ('D', 'D')], max_length=5)),
                ('error_code', models.IntegerField(max_length=5)),
                ('details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='parameter',
            name='description',
            field=models.TextField(blank=True, help_text='Enter the Parameter Description', max_length=1000, null=True, verbose_name='Parameter Description'),
        ),
    ]
