# Generated by Django 2.1.7 on 2019-03-01 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('process_scada', '0002_auto_20190301_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, help_text='Enter the date and time for the event', verbose_name='Date and Time')),
                ('types', models.CharField(choices=[('P', 'P'), ('E', 'E')], help_text='Enter the type', max_length=5, verbose_name='Type')),
                ('quantity', models.PositiveIntegerField(help_text='Enter the production quantity in x1000', verbose_name='Quantity')),
                ('comp_mmv', models.CharField(help_text='Enter the Compression force M,MV', max_length=10, verbose_name='Compression Force ( M MV)')),
                ('comp_srel', models.CharField(help_text='Enter compression force Srel %', max_length=10, verbose_name='Compression force( SRel %)')),
                ('comp_pmv', models.CharField(help_text='Enter the compression force P MV', max_length=10, verbose_name='Compression Force ( P MV) ')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='details',
            field=models.TextField(blank=True, help_text='Enter the Details of Diagnosis', null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_filter',
            field=models.CharField(choices=[('S', 'S'), ('W', 'W'), ('D', 'D')], help_text='Choose the diagnosis filter', max_length=5),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='error_code',
            field=models.IntegerField(help_text='Enter the Error Code', verbose_name='Error Code'),
        ),
    ]
